// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

package movie_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Pagination struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{1}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type MovieId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieId) Reset()         { *m = MovieId{} }
func (m *MovieId) String() string { return proto.CompactTextString(m) }
func (*MovieId) ProtoMessage()    {}
func (*MovieId) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{2}
}

func (m *MovieId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieId.Unmarshal(m, b)
}
func (m *MovieId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieId.Marshal(b, m, deterministic)
}
func (m *MovieId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieId.Merge(m, src)
}
func (m *MovieId) XXX_Size() int {
	return xxx_messageInfo_MovieId.Size(m)
}
func (m *MovieId) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieId.DiscardUnknown(m)
}

var xxx_messageInfo_MovieId proto.InternalMessageInfo

func (m *MovieId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Movie struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Director             string   `protobuf:"bytes,4,opt,name=director,proto3" json:"director,omitempty"`
	Year                 int32    `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Plot                 string   `protobuf:"bytes,6,opt,name=plot,proto3" json:"plot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{3}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Movie) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *Movie) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Movie) GetPlot() string {
	if m != nil {
		return m.Plot
	}
	return ""
}

type MovieList struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieList) Reset()         { *m = MovieList{} }
func (m *MovieList) String() string { return proto.CompactTextString(m) }
func (*MovieList) ProtoMessage()    {}
func (*MovieList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{4}
}

func (m *MovieList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieList.Unmarshal(m, b)
}
func (m *MovieList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieList.Marshal(b, m, deterministic)
}
func (m *MovieList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieList.Merge(m, src)
}
func (m *MovieList) XXX_Size() int {
	return xxx_messageInfo_MovieList.Size(m)
}
func (m *MovieList) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieList.DiscardUnknown(m)
}

var xxx_messageInfo_MovieList proto.InternalMessageInfo

func (m *MovieList) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func (m *MovieList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "movie_service.Empty")
	proto.RegisterType((*Pagination)(nil), "movie_service.Pagination")
	proto.RegisterType((*MovieId)(nil), "movie_service.MovieId")
	proto.RegisterType((*Movie)(nil), "movie_service.Movie")
	proto.RegisterType((*MovieList)(nil), "movie_service.MovieList")
}

func init() {
	proto.RegisterFile("movie.proto", fileDescriptor_fde087a4194eda75)
}

var fileDescriptor_fde087a4194eda75 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x69, 0xd3, 0x36, 0x13, 0x3f, 0x70, 0x29, 0xb2, 0xcd, 0xa9, 0xe4, 0xd4, 0x83, 0xe4,
	0x50, 0x41, 0x94, 0x5e, 0xc4, 0x0f, 0xa4, 0x60, 0x51, 0x22, 0x5e, 0xbc, 0x48, 0xcc, 0x0e, 0x65,
	0x21, 0xed, 0x86, 0xcd, 0x5a, 0xe8, 0xef, 0xf0, 0xf7, 0xf8, 0xdf, 0x64, 0x27, 0xb6, 0xda, 0x90,
	0x83, 0x78, 0x9b, 0x37, 0xef, 0xcd, 0xcb, 0x9b, 0xd9, 0x40, 0xb0, 0x50, 0x2b, 0x89, 0x71, 0xa1,
	0x95, 0x51, 0x6c, 0x9f, 0xc0, 0x6b, 0x89, 0x7a, 0x25, 0x33, 0x8c, 0xba, 0xe0, 0xdd, 0x2e, 0x0a,
	0xb3, 0x8e, 0xce, 0x00, 0x1e, 0xd3, 0xb9, 0x5c, 0xa6, 0x46, 0xaa, 0x25, 0x63, 0xd0, 0x2e, 0xd2,
	0x39, 0x72, 0x67, 0xe8, 0x8c, 0xbc, 0x84, 0x6a, 0xd6, 0x07, 0x2f, 0x97, 0x0b, 0x69, 0xb8, 0x4b,
	0xcd, 0x0a, 0x44, 0x03, 0xe8, 0xce, 0xac, 0xe3, 0x54, 0xb0, 0x03, 0x70, 0xa5, 0xa0, 0x11, 0x3f,
	0x71, 0xa5, 0x88, 0x3e, 0x1c, 0xf0, 0x88, 0xab, 0x33, 0xd6, 0xca, 0x48, 0x93, 0x23, 0x59, 0xf9,
	0x49, 0x05, 0xd8, 0x10, 0x02, 0x81, 0x65, 0xa6, 0x65, 0x61, 0x33, 0xf0, 0x16, 0x71, 0xbf, 0x5b,
	0x2c, 0x84, 0x9e, 0x90, 0x1a, 0x33, 0xa3, 0x34, 0x6f, 0x13, 0xbd, 0xc5, 0x36, 0xf2, 0x1a, 0x53,
	0xcd, 0xbd, 0x2a, 0xb2, 0xad, 0x69, 0x8d, 0x5c, 0x19, 0xde, 0x21, 0x2d, 0xd5, 0xd1, 0x03, 0xf8,
	0x14, 0xea, 0x5e, 0x96, 0x86, 0x9d, 0x40, 0x87, 0xee, 0x51, 0x72, 0x67, 0xd8, 0x1a, 0x05, 0xe3,
	0x7e, 0xbc, 0x73, 0x9e, 0x98, 0x94, 0xc9, 0xb7, 0xc6, 0xc6, 0xce, 0xd4, 0xfb, 0x72, 0x7b, 0x01,
	0x02, 0xe3, 0x4f, 0x17, 0xf6, 0x48, 0xf7, 0x54, 0x0d, 0xb1, 0x0b, 0x08, 0xae, 0x35, 0xa6, 0x06,
	0xab, 0xe5, 0x1b, 0x3d, 0xc3, 0x7a, 0x97, 0x5e, 0x81, 0x5d, 0x82, 0x7f, 0x87, 0x66, 0x56, 0x7d,
	0x6e, 0x50, 0x93, 0xfc, 0xbc, 0x4f, 0xc8, 0x9b, 0x3c, 0x69, 0xa3, 0x73, 0xe8, 0x6d, 0x1c, 0xd8,
	0x71, 0x93, 0x6a, 0x2a, 0xc2, 0xc6, 0x44, 0x36, 0xf6, 0x73, 0x21, 0xfe, 0x15, 0x7b, 0x02, 0xc1,
	0x0d, 0xe6, 0xb8, 0x19, 0xfd, 0xeb, 0x77, 0x69, 0xf8, 0xea, 0xe8, 0xe5, 0x30, 0x9e, 0xec, 0x10,
	0x6f, 0x1d, 0xfa, 0x57, 0x4f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x48, 0xf2, 0x32, 0xba,
	0x02, 0x00, 0x00,
}
